Added the student response CSV file and the PDF file
oss-slu/bubble_scan pull request #111
Opened 2024-10-28 18:20 UTC by yildizahmetali

Fixes #92 

**What was changed?**
Created a new folder named StudentResponses and added two files: studentResponses pdf file and studentAnswers csv file. Which can be used to comparation.

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*

The folder I created is under the InputData folder.
[bubble_scans_50_5.pdf](https://github.com/user-attachments/files/17547189/bubble_scans_50_5.pdf)
[bubblescan_answers_50.csv](https://github.com/user-attachments/files/17547190/bubblescan_answers_50.csv)

**Why was it changed?**

We needed these data to test whether our algorithm works efficiently and correctly.

2024-10-28 22:42 UTC, ramezmosad reviewed
I checked out your branch and ran the program, and that didn't cause any errors. I also see the StudentResponses PDF and StudentAnswers CSV file under the InputData directory and they both look good. I believe everything looks good! Great job!!

2024-10-29 14:54 UTC, kate-holdener commented
@yildizahmetali You need to stop committing files that should not be committed. Look at the "Files changed" tab of your PR!

2024-10-29 14:55 UTC, kate-holdener commented
@yildizahmetali You are missing the script for comparing the expected with actual

2024-10-29 21:31 UTC, Chirag2x commented on .DS_Store
@yildizahmetali, Please try to reactor your code and be informative wha you are adding. The same file was also added last time by team mates then we had to refactor again. So be careful, we may generate bunch of garbled files into the main.

2024-10-29 21:34 UTC, Chirag2x requested changes
Why did I am seeing more than 800 files for review. Refactor this and add only things which is important, I believe it should be Original PDF, Respective CSV files, and the script for the comparison, For the script you know the format of output you are gonna get from bubble Scan and you have your csv. So this would be easy task to develop. We are gonna use it in near future.

2024-10-29 21:36 UTC, Chirag2x commented
Due to the additional file we are having a merge conflicts.

2024-11-05 02:33 UTC, Chirag2x commented on .DS_Store
Yes, Good Job.

2024-11-05 05:00 UTC, closed without merging